# Generated by Django 5.1.2 on 2024-10-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_remove_quiz_end_time_remove_quiz_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='participant',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='participantanswer',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='score',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='participantanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='score',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizapp.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='ParticipantAnswer',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
